"use client";

import "./globals.css";
import { Inter } from "next/font/google";
import Navigation from "@/components/Navigation";
import FinanceContextProvider from "@/libs/store/finance-context";
import AuthContextProvider from "@/libs/store/auth-context";

import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Finance Tracker",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Finance Tracker</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body className={inter.className}>
        <AuthContextProvider>
          <FinanceContextProvider>
            <ToastContainer />
            <Navigation />
            {children}
          </FinanceContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
